// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/en.json.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('en', {
    "PaymentDialog.MultiCaptureInfo" : "You can capture up to {Amount}.",
    "PaymentDialog.SingleCaptureInfo" : "You can capture up to {Amount}. Further captures on this payment aren't possible, make sure to capture exactly the required amount!",
    "PaymentDialog.FullCaptureInfo" : "You're about to capture {Amount}. This action cannot be undone.",
    "PaymentDialog.CaptureAmount" : "Capture amount",
    "PaymentDialog.MultiRefundInfo" : "You can refund up to {Amount}.",
    "PaymentDialog.SingleRefundInfo" : "You can refund up to {Amount}. Further refunds on this payment aren't possible, make sure to refund exactly the required amount!",
    "PaymentDialog.FullRefundInfo" : "You're about to refund {Amount}. This action cannot be undone.",
    "PaymentDialog.RefundAmount" : "Refund amount",
    "PaymentDialog.VoidInfo" : "Void this payment ({Amount}). This action cannot be undone.",
    "PaymentDialog.VoidPayment" : "Void payment",
    "PaymentDialog.Cancel" : "Cancel",
    "PaymentDialog.Amount" : "Amount"
}
);
}